id = "rootd"
kind = "service"
execution_domain = "user"
startup = "none"

[build]
builder = "cargo-kernel-binary"
package = "rootd"

[install]
path = "services/rootd/rootd.elf"

[[desktop.entries]]
display_name = "rootd"
weight_micros = 100
logical_admin = true
console_hosted = false
