id = "prekernel"
kind = "boot"
execution_domain = "kernel"
profiles = ["default"]

[build]
builder = "prekernel-rustc"
package = "prekernel"

[install]
path = "prekernel.elf"

[boot]
preload = false
required = true
priority = -2000

startup = "none"
