//! Planning-only inventory for Linux `.ko` slow-path ring3 migration.
//!
//! This file is intentionally not linked into the driver module.  `cargo xtask
//! ring3-inventory` scans it as source-of-truth planning data so the active
//! `.ko` compatibility files can remain whole-file ring0 substrate exceptions
//! while their sleepable policy/state slow paths are tracked as ring3 work.

// RING3-MIGRATION-REFERENCE START: Linux .ko slow-path brokerization candidates.
// Keep Linux .ko text execution, IRQ callbacks, DMA/MMIO touching helpers, and
// atomic/hot callbacks in ring0.  Migrate only sleepable init/probe/state
// decisions into driverd through bounded broker events and RustOS-private
// driver broker syscalls.
#[allow(dead_code)]
struct KoSlowPathMigrationReference {
    area: &'static str,
    ring0_broker_scope: &'static str,
    ring3_owner: &'static str,
    symbols: &'static [&'static str],
    first_step: &'static str,
    fallback_removal_gate: &'static str,
}

#[allow(dead_code)]
const KO_SLOW_PATH_RING3_BATCHES: &[KoSlowPathMigrationReference] = &[
    KoSlowPathMigrationReference {
        area: "pci probe/init resource policy",
        ring0_broker_scope: "PCI config-space/MMIO/BAR mutation and .ko probe callback execution",
        ring3_owner: "driverd",
        symbols: &[
            "__pci_register_driver",
            "pci_enable_device",
            "pcim_enable_device",
            "pci_disable_device",
            "pci_set_master",
            "pci_clear_master",
            "pci_write_config_byte",
            "pci_write_config_word",
            "pci_write_config_dword",
            "pci_iomap",
            "pci_iomap_wc",
            "pci_iounmap",
        ],
        first_step: "record bounded symbol events and let driverd own admission/state policy",
        fallback_removal_gate: "QEMU profile with PCI .ko module proves no direct policy fallback is used",
    },
    KoSlowPathMigrationReference {
        area: "USB driver/interface admission",
        ring0_broker_scope: "host-controller transfer rings, endpoint reset, URB transfer execution",
        ring3_owner: "driverd/devmgrd/inputd",
        symbols: &[
            "usb_register_driver",
            "usb_deregister",
            "usb_alloc_urb",
            "usb_free_urb",
            "usb_control_msg",
            "usb_interrupt_msg",
            "usb_set_interface",
            "usb_driver_claim_interface",
            "usb_driver_release_interface",
        ],
        first_step: "broker interface bind/unbind/resource snapshots to driverd before policy state changes",
        fallback_removal_gate: "usbhid load and HID input smoke pass with ring0 only executing transfer substrate",
    },
    KoSlowPathMigrationReference {
        area: "HID device model and report parsing policy",
        ring0_broker_scope: "HID .ko callbacks, raw report buffer access, input ingress handoff",
        ring3_owner: "driverd/inputd",
        symbols: &[
            "__hid_register_driver",
            "hid_unregister_driver",
            "hid_parse_report",
            "hid_hw_start",
            "hid_hw_stop",
            "hid_hw_open",
            "hid_hw_close",
            "hidinput_connect",
            "hidinput_disconnect",
        ],
        first_step: "move match/report/topology policy snapshots to driverd and event policy to inputd",
        fallback_removal_gate: "keyboard and pointer smoke pass with HID policy events consumed in ring3",
    },
    KoSlowPathMigrationReference {
        area: "serio and PS/2 bind policy",
        ring0_broker_scope: "serio port callbacks, PS/2 command execution, interrupt/input ingress",
        ring3_owner: "driverd/inputd",
        symbols: &[
            "__serio_register_driver",
            "serio_unregister_driver",
            "serio_open",
            "serio_close",
            "serio_write",
            "ps2_command",
            "ps2_begin_command",
            "ps2_end_command",
        ],
        first_step: "broker port discovery and driver match decisions to driverd",
        fallback_removal_gate: "psmouse/serio profile proves bind decisions no longer use ring0 policy fallback",
    },
    KoSlowPathMigrationReference {
        area: "Linux device model registration policy",
        ring0_broker_scope: "compat object layout, refcount storage, callback execution needed by .ko ABI",
        ring3_owner: "driverd/devmgrd",
        symbols: &[
            "driver_register",
            "driver_unregister",
            "device_register",
            "device_unregister",
            "bus_register",
            "bus_unregister",
            "class_register",
            "class_unregister",
            "bus_register_notifier",
            "bus_unregister_notifier",
        ],
        first_step: "mirror driver/device/bus/class lifecycle as broker events and let driverd own namespace policy",
        fallback_removal_gate: "module load/unload cycles leave no driver/device namespace state owned only by ring0",
    },
    KoSlowPathMigrationReference {
        area: "virtio and DRM setup policy",
        ring0_broker_scope: "virtqueue kick/notify, PCI/MMIO access, framebuffer present substrate",
        ring3_owner: "driverd/uiserver/netd",
        symbols: &[
            "__register_virtio_driver",
            "unregister_virtio_driver",
            "vring_create_virtqueue",
            "virtio_device_ready",
            "drm_dev_alloc",
            "drm_dev_register",
            "drm_dev_unregister",
            "drm_mode_config_init",
            "drm_fbdev_generic_setup",
        ],
        first_step: "broker device readiness, queue topology, DRM object lifecycle, and provider selection to services",
        fallback_removal_gate: "virtio-gpu/virtio-drm and virtio-net profiles boot without native legacy fallback",
    },
    KoSlowPathMigrationReference {
        area: "netdev registration and carrier policy",
        ring0_broker_scope: "packet buffer ABI, NAPI callback substrate, DMA mapping broker",
        ring3_owner: "driverd/netd",
        symbols: &[
            "alloc_etherdev_mqs",
            "free_netdev",
            "register_netdev",
            "register_netdevice",
            "unregister_netdev",
            "netif_carrier_on",
            "netif_carrier_off",
            "netif_tx_wake_queue",
            "netif_tx_stop_queue",
        ],
        first_step: "move netdev lifetime, queue/carrier state, and interface admission into netd/driverd",
        fallback_removal_gate: "virtio-net smoke shows netd owns interface state and ring0 only bridges packet substrate",
    },
    KoSlowPathMigrationReference {
        area: "DMA/MMIO/devres lease policy",
        ring0_broker_scope: "actual DMA address translation, IOMMU/MMIO mapping, IRQ-safe free paths",
        ring3_owner: "driverd/devmgrd",
        symbols: &[
            "dma_set_mask",
            "dma_set_coherent_mask",
            "dma_alloc_attrs",
            "dma_free_attrs",
            "dma_map_page_attrs",
            "dma_unmap_page_attrs",
            "ioremap",
            "ioremap_wc",
            "devm_ioremap",
            "devm_request_threaded_irq",
        ],
        first_step: "turn resource acquisition/release into driverd-owned leases while ring0 performs privileged mapping",
        fallback_removal_gate: "module removal proves devres cleanup is lease-driven and late frees fail closed",
    },
    KoSlowPathMigrationReference {
        area: "workqueue and timer lifecycle policy",
        ring0_broker_scope: "callback execution, timer interrupt substrate, waitqueue wake mechanics",
        ring3_owner: "driverd",
        symbols: &[
            "alloc_workqueue",
            "destroy_workqueue",
            "__flush_workqueue",
            "queue_work_on",
            "queue_delayed_work_on",
            "mod_timer",
            "del_timer",
            "del_timer_sync",
        ],
        first_step: "broker creation/destruction and bounded quiesce state, not hot callback dispatch",
        fallback_removal_gate: "module unload and timeout tests show no unbounded ring0 policy wait remains",
    },
    KoSlowPathMigrationReference {
        area: "module export and symbol allow-list policy",
        ring0_broker_scope: "ELF relocation, executable mapping, trampoline generation, ABI-preserving symbol address return",
        ring3_owner: "driverd",
        symbols: &[
            "resolve_linux_symbol",
            "register_module_exports",
            "module_init",
            "module_exit",
            "MODULE_ALIAS",
            "MODULE_LICENSE",
        ],
        first_step: "make driverd own symbol/event allow-list policy while ring0 keeps relocation and broker enforcement",
        fallback_removal_gate: "autoload rejects unknown symbols from driverd policy without ring0 compatibility fallback",
    },
];
// RING3-MIGRATION-REFERENCE END: Linux .ko slow-path brokerization candidates.
