use fontdue::{Font, FontSettings, Metrics};
use std::env;
use std::error::Error;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

mod shared {
    include!("../../tools/build_log_cfg.rs");
}

const ASCII_START: u8 = 32;
const ASCII_END: u8 = 126;

struct AtlasSpec<'a> {
    const_name: &'a str,
    font_path: &'a str,
    px: f32,
    line_height: Option<usize>,
    monospace: bool,
}

struct GlyphEntry {
    width: usize,
    height: usize,
    advance: usize,
    atlas_offset: usize,
}

struct RasterAtlas {
    const_name: &'static str,
    line_height: usize,
    cell_width: usize,
    monospace: bool,
    glyphs: Vec<GlyphEntry>,
    alpha: Vec<u8>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR")?);
    let repo_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .ok_or("failed to resolve repo root from CARGO_MANIFEST_DIR")?;
    let fonts_dir = repo_root.join("assets/ui/fonts");
    let logging_path = repo_root.join("config/logging.toml");
    let log_cfg_path = repo_root.join("tools/build_log_cfg.rs");
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);
    let out_path = out_dir.join("generated_fonts.rs");

    println!("cargo:rerun-if-changed={}", logging_path.display());
    println!("cargo:rerun-if-changed={}", log_cfg_path.display());
    let logging = fs::read_to_string(&logging_path)?;
    shared::emit_log_cfgs(&logging);

    let specs = [
        AtlasSpec {
            const_name: "UI_LARGE",
            font_path: "Rajdhani-SemiBold.ttf",
            px: 18.0,
            line_height: Some(22),
            monospace: false,
        },
        AtlasSpec {
            const_name: "UI_MEDIUM",
            font_path: "Rajdhani-SemiBold.ttf",
            px: 16.0,
            line_height: Some(20),
            monospace: false,
        },
        AtlasSpec {
            const_name: "UI_SMALL",
            font_path: "Rajdhani-SemiBold.ttf",
            px: 14.0,
            line_height: Some(18),
            monospace: false,
        },
        AtlasSpec {
            const_name: "TERMINAL",
            font_path: "IosevkaTerm-Regular.ttf",
            px: 16.0,
            line_height: Some(20),
            monospace: true,
        },
    ];

    let mut atlases = Vec::with_capacity(specs.len());
    for spec in specs {
        let font_path = fonts_dir.join(spec.font_path);
        println!("cargo:rerun-if-changed={}", font_path.display());
        atlases.push(build_atlas(spec, &font_path)?);
    }

    let mut output = String::new();
    output.push_str("// @generated by services/uiserver/build.rs\n");
    output.push_str("// Do not edit by hand.\n\n");
    for atlas in atlases {
        write_atlas(&mut output, &atlas)?;
    }
    fs::write(out_path, output)?;
    Ok(())
}

fn build_atlas(spec: AtlasSpec<'static>, font_path: &Path) -> Result<RasterAtlas, Box<dyn Error>> {
    let bytes = fs::read(font_path)?;
    let font = Font::from_bytes(bytes, FontSettings::default())
        .map_err(|err| format!("failed to parse {}: {:?}", font_path.display(), err))?;
    let line_metrics = font
        .horizontal_line_metrics(spec.px)
        .ok_or_else(|| format!("font has no horizontal metrics: {}", font_path.display()))?;

    let natural_line_height = line_metrics.new_line_size.ceil().max(1.0) as usize;
    let line_height = spec.line_height.unwrap_or(natural_line_height);
    let baseline = line_metrics.ascent.ceil() as isize
        + line_height.saturating_sub(natural_line_height) as isize / 2;

    let mut rasterized = Vec::with_capacity((ASCII_END - ASCII_START + 1) as usize);
    let mut monospace_width = 0usize;
    for byte in ASCII_START..=ASCII_END {
        let ch = byte as char;
        let (metrics, bitmap) = font.rasterize(ch, spec.px);
        let width = measured_cell_width(&metrics, spec.monospace);
        if spec.monospace {
            monospace_width = monospace_width.max(width.max(metrics.advance_width.ceil() as usize));
        }
        rasterized.push((metrics, bitmap, width));
    }

    let cell_width = if spec.monospace {
        monospace_width.max(1)
    } else {
        0
    };

    let mut glyphs = Vec::with_capacity(rasterized.len());
    let mut alpha = Vec::new();
    for (metrics, bitmap, measured_width) in rasterized {
        let glyph_width = if spec.monospace {
            cell_width
        } else {
            measured_width.max(1)
        };
        let atlas_offset = alpha.len();
        let cell = rasterize_glyph_cell(
            glyph_width,
            line_height,
            baseline,
            spec.monospace,
            &metrics,
            &bitmap,
        );
        alpha.extend_from_slice(cell.as_slice());
        glyphs.push(GlyphEntry {
            width: glyph_width,
            height: line_height,
            advance: glyph_width,
            atlas_offset,
        });
    }

    Ok(RasterAtlas {
        const_name: spec.const_name,
        line_height,
        cell_width,
        monospace: spec.monospace,
        glyphs,
        alpha,
    })
}

fn measured_cell_width(metrics: &Metrics, monospace: bool) -> usize {
    if monospace {
        return metrics.advance_width.ceil().max(1.0) as usize;
    }
    let left = if metrics.xmin < 0 {
        (-metrics.xmin) as usize
    } else {
        metrics.xmin as usize
    };
    let visible = left.saturating_add(metrics.width);
    visible
        .max(metrics.advance_width.ceil().max(1.0) as usize)
        .saturating_add(1)
}

fn rasterize_glyph_cell(
    glyph_width: usize,
    line_height: usize,
    baseline: isize,
    monospace: bool,
    metrics: &Metrics,
    bitmap: &[u8],
) -> Vec<u8> {
    let mut cell = vec![0u8; glyph_width.saturating_mul(line_height)];
    if metrics.width == 0 || metrics.height == 0 || bitmap.is_empty() {
        return cell;
    }

    let top = baseline - metrics.height as isize - metrics.ymin as isize;
    let left = if monospace {
        glyph_width.saturating_sub(metrics.width) / 2
    } else if metrics.xmin < 0 {
        (-metrics.xmin) as usize
    } else {
        metrics.xmin as usize
    };

    for row in 0..metrics.height {
        let dst_y = top + row as isize;
        if dst_y < 0 || dst_y >= line_height as isize {
            continue;
        }
        let src_start = row.saturating_mul(metrics.width);
        let src_end = src_start.saturating_add(metrics.width);
        let src_row = &bitmap[src_start..src_end];

        if left >= glyph_width {
            continue;
        }
        let copy_width = metrics.width.min(glyph_width.saturating_sub(left));
        let dst_start = dst_y as usize * glyph_width + left;
        let dst_end = dst_start + copy_width;
        cell[dst_start..dst_end].copy_from_slice(&src_row[..copy_width]);
    }

    cell
}

fn write_atlas(output: &mut String, atlas: &RasterAtlas) -> Result<(), Box<dyn Error>> {
    writeln!(
        output,
        "pub(crate) const {}_LINE_HEIGHT: usize = {};",
        atlas.const_name, atlas.line_height
    )?;
    writeln!(
        output,
        "pub(crate) const {}_CELL_WIDTH: usize = {};",
        atlas.const_name, atlas.cell_width
    )?;
    writeln!(
        output,
        "pub(crate) const {}_MONOSPACE: bool = {};",
        atlas.const_name, atlas.monospace
    )?;
    writeln!(
        output,
        "pub(crate) static {}_GLYPHS: [GlyphMetrics; {}] = [",
        atlas.const_name,
        atlas.glyphs.len()
    )?;
    for glyph in &atlas.glyphs {
        writeln!(
            output,
            "    GlyphMetrics {{ width: {}, height: {}, advance: {}, atlas_offset: {} }},",
            glyph.width, glyph.height, glyph.advance, glyph.atlas_offset
        )?;
    }
    output.push_str("];\n");
    writeln!(
        output,
        "pub(crate) static {}_ALPHA: &[u8] = &[",
        atlas.const_name
    )?;
    for chunk in atlas.alpha.chunks(24) {
        output.push_str("    ");
        for byte in chunk {
            write!(output, "{byte},")?;
        }
        output.push('\n');
    }
    output.push_str("];\n\n");
    Ok(())
}
