[package]
name = "uiserver"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
fontdue = "0.9.3"

[dependencies]
driver-domain-protocol = { path = "../../libs/driver-domain-protocol" }
observability-client = { path = "../../libs/observability-client" }
rustos-svc-runtime = { path = "../../libs/rustos-svc-runtime" }
rustos-user-abi = { path = "../../libs/rustos-user-abi" }
embedded-graphics = "0.8"
keyboard-core = { path = "../../drivers/libs/keyboard-core" }
libc = "0.2"
runtime-control = { path = "../../libs/runtime-control" }
vte = { version = "0.15.0", default-features = false }
wayland-protocols = { version = "0.32.12", features = ["server", "unstable"] }
wayland-server = "0.31.13"
