[package]
name = "uiserver"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
fontdue = "0.9.3"

[dependencies]
embedded-graphics = "0.8"
vte = { version = "0.15.0", default-features = false }
wayland-protocols = { version = "0.32.12", features = ["server", "unstable"] }
wayland-server = "0.31.13"
