[package]
name = "kernel-ps"
version = "0.1.0"
edition = "2024"

[dependencies]
nucleus-core = { path = "../nucleus-core" }
kernel-lowlevel = { path = "../lowlevel" }
kernel-hal = { path = "../hal" }
kernel-mm = { path = "../mm" }
kernel-ipc-runtime = { path = "../ipc-runtime" }
kernel-object = { path = "../object" }
trace-loc-macro = { path = "../../libs/trace-loc-macro" }
rustos-user-abi = { path = "../../libs/rustos-user-abi", features = ["linux-compat-state"] }
lazy_static = { version = "1.4", features = ["spin_no_std"] }
spin = "0.10.0"
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions", "abi_x86_interrupt"] }

[dev-dependencies]
boot-random = { path = "../../libs/boot-random", features = ["deterministic-test-seed"] }
kernel-ipc-runtime = { path = "../ipc-runtime", features = ["host-test"] }
