[book]
title = "RustOS Documentation"
authors = ["RustOS contributors"]
src = "docs"
language = "en"
multilingual = false

[build]
build-dir = "build/mdbook"

[output.html]
git-repository-url = "https://github.com/ierwarf/rustos"
site-url = "/rustos/"
