[workspace]

members = [
    "bootloader",
    "bootloader/boot-protocol",
    "crates/boot-random",
    "crates/boot-storage",
    "crates/driver-module-runtime",
    "crates/keyboard-core",
    "driver-abi",
    "drivers/display/bootfb",
    "drivers/display/amdgpu",
    "drivers/input/keyboard",
    "kernel",
    "module-tests",
    "prekernel",
    "uiserver",
    "xtask",
]
resolver = "3"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
