[workspace]

members = [
    "boot/bootloader",
    "boot/bootloader/boot-protocol",
    "boot/prekernel",
    "shared/boot-random",
    "shared/storage-core",
    "shared/storage-fat",
    "core/kernel",
    "system/packages/uiserver",
    "drivers/driver-abi",
    "drivers/driver-module-runtime",
    "drivers/display/bootfb",
    "drivers/display/amdgpu",
    "drivers/input/keyboard-core",
    "drivers/input/keyboard",
    "tests/module-tests",
    "tools/xtask",
]
resolver = "3"

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"
