id = "syscalld"
kind = "service"
execution_domain = "user"
profiles = ["default"]
startup = "none"

[build]
builder = "cargo-kernel-binary"
package = "syscalld"
linkage = "static-pie"

[install]
path = "services/syscalld/syscalld.elf"

[boot]
preload = true
required = false
priority = -590

[[desktop.entries]]
display_name = "syscalld"
weight_micros = 50
logical_admin = true
console_hosted = false
