id = "inputd"
kind = "service"
execution_domain = "user"
profiles = ["default"]
startup = "init"

[build]
builder = "cargo-kernel-binary"
package = "inputd"

[install]
path = "services/inputd/inputd.elf"

[[desktop.entries]]
display_name = "inputd"
weight_micros = 2000
logical_admin = true
console_hosted = false
