id = "userdemo2"
kind = "app"
execution_domain = "user"
profiles = ["default"]
startup = "none"

[build]
builder = "mingw-c-exe"
source = "winmain.c"

[install]
path = "apps/windows/userdemo2/userdemo2.exe"

[[desktop.entries]]
display_name = "userdemo2.exe"
weight_micros = 100
