[package]
name = "boot-storage"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
boot-protocol = { path = "../../bootloader/boot-protocol" }
fatfs = { git = "https://github.com/rafalh/rust-fatfs", default-features = false, features = ["alloc", "lfn"] }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions"] }
