[package]
name = "nucleus"
version = "0.1.0"
edition = "2024"

[dependencies]
kernel-base = { path = "./base" }
kernel-hal = { path = "./hal" }
kernel-mm = { path = "./mm" }
kernel-executive = { path = "./executive" }
boot-protocol = { path = "../boot/bootloader/boot-protocol" }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
