id = "nucleus"
kind = "kernel"
execution_domain = "kernel"
profiles = ["default"]

[build]
builder = "kernel-rustc"
package = "nucleus"

[install]
path = "nucleus.elf"

[boot]
preload = true
required = true
priority = -1900

startup = "none"
