id = "storaged"
kind = "service"
execution_domain = "user"
profiles = ["default"]
startup = "init"

[build]
builder = "cargo-kernel-binary"
package = "storaged"

[install]
path = "services/storaged/storaged.elf"

[boot]
preload = true
required = false
priority = -575

[[desktop.entries]]
display_name = "storaged"
weight_micros = 100
logical_admin = true
console_hosted = false
