[package]
name = "kernel-executive"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
nucleus-core = { path = "../nucleus-core" }
kernel-hal = { path = "../hal" }
kernel-mm = { path = "../mm" }
kernel-object = { path = "../object" }
kernel-ps = { path = "../ps" }
kernel-io-manager = { path = "../io-manager", default-features = false }
kernel-compat = { path = "../compat" }
boot-protocol = { path = "../../boot/boot-protocol" }
driver-abi = { path = "../../drivers/libs/driver-abi" }
storage-core = { path = "../../libs/storage-core" }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
