id = "vfsd"
kind = "service"
execution_domain = "user"
profiles = ["default"]
startup = "none"

[build]
builder = "cargo-kernel-binary"
package = "vfsd"
linkage = "static-pie"

[install]
path = "services/vfsd/vfsd.elf"

[boot]
preload = true
required = false
priority = -589

[[desktop.entries]]
display_name = "vfsd"
weight_micros = 50
logical_admin = true
console_hosted = false
