[package]
name = "kernel-io-manager"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
rustos_export_driver_symbols = []

[dependencies]
nucleus-core = { path = "../nucleus-core" }
kernel-hal = { path = "../hal" }
kernel-mm = { path = "../mm" }
kernel-object = { path = "../object" }
kernel-ipc-runtime = { path = "../ipc-runtime" }
kernel-ps = { path = "../ps" }
boot-protocol = { path = "../../boot/boot-protocol" }
driver-domain-protocol = { path = "../../libs/driver-domain-protocol" }
driver-abi = { path = "../../drivers/libs/driver-abi" }
input-evdev = { path = "../../drivers/libs/input-evdev" }
keyboard-core = { path = "../../drivers/libs/keyboard-core" }
rustos-user-abi = { path = "../../libs/rustos-user-abi" }
embedded-graphics = { version = "0.8", default-features = false }
elf = { version = "0.8.0", default-features = false }
hidreport = { version = "0.6.0", default-features = false }
heapless = { version = "0.9.3", default-features = false }
object = { version = "0.38.1", default-features = false, features = ["read_core", "elf"] }
sha2 = { version = "0.10", default-features = false }
smoltcp = { version = "=0.13.0", default-features = false, features = ["alloc", "medium-ethernet", "proto-ipv4", "socket-tcp", "socket-udp"] }
spin = "0.10.0"
tock-registers = { version = "0.10.1", default-features = false }
virtio-drivers = { version = "0.13.0", default-features = false }
vte = { version = "0.15.0", default-features = false }
x86_64 = { version = "0.15.4", default-features = false, features = ["instructions", "abi_x86_interrupt"] }
xhci = { version = "0.9.2", default-features = false }
zerocopy = { version = "0.8.40", default-features = false, features = ["derive"] }
