id = "wayclick"
kind = "app"
execution_domain = "user"
profiles = ["default"]

[build]
builder = "cargo-kernel-binary"
package = "wayclick"

[install]
path = "apps/wayclick/wayclick.elf"

[boot]
preload = false
required = false
priority = 100

startup = "none"

[[desktop.entries]]
display_name = "WayClick"
weight_micros = 50
console_hosted = false
