id = "wayclick"
kind = "app"
execution_domain = "user"

[build]
builder = "cargo-kernel-binary"
package = "wayclick"

[install]
path = "apps/wayclick/wayclick.elf"


[[desktop.entries]]
display_name = "WayClick"
weight_micros = 100
console_hosted = false
