[package]
name = "module-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
boot-protocol = { path = "../bootloader/boot-protocol" }
boot-random = { path = "../crates/boot-random" }
boot-storage = { path = "../crates/boot-storage" }
driver-abi = { path = "../driver-abi" }
keyboard-core = { path = "../crates/keyboard-core" }
