[package]
name = "runtimed"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
observability-client = { path = "../../libs/observability-client" }
libc = "0.2"
runtime-control = { path = "../../libs/runtime-control" }
rustos-user-abi = { path = "../../libs/rustos-user-abi", features = ["linux-compat-state"] }
